name: NGO CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: list files
        run: ls -a
      
      - name: Check required files
        run: |
          test -f Home.html
          test -d CSS
          test -d JS
      