name: NGO CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Check required files
        run: |
          test -f Home.html
          test -d CSS
          test -d js
